
@baseUrl = http://localhost:8000
@json = Content-Type: application/json

# GET USERS
GET {{baseUrl}}/users

###

# SUBMIT TRADE
POST {{baseUrl}}/orders
{{json}}

{
  "user_id": 1,
  "symbol": "AAPL",
  "side": "buy",
  "quantity": 20,
  "price": 15
}

###

# HEALTH CHECK
GET {{baseUrl}}/health

###

# GET PORTFOLIO BALANCE
GET {{baseUrl}}/portfolio?account_id=1
{{json}}
