
@baseUrl = http://localhost:8000
@json = Content-Type: application/json

# GET USERS
GET {{baseUrl}}/users

###

# SUBMIT TRADE
POST {{baseUrl}}/orders
{{json}}

{
  "user_id": 1,
  "symbol": "AAPL",
  "side": "sell",
  "quantity": 900,
  "price": 100
}

###

# HEALTH CHECK
GET {{baseUrl}}/health

