"""fix order primary key

Revision ID: 8b0130916df1
Revises: 889f28c4c0dd
Create Date: 2026-03-08 16:28:11.405040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b0130916df1'
down_revision: Union[str, Sequence[str], None] = '889f28c4c0dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False))
    op.drop_column('orders', 'id')
    op.drop_column('orders', 'qty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('qty', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('orders', 'quantity')
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###
